# vim: sw=2 ts=2:

language: elixir

elixir:
  - "1.8"
  - "1.9"

otp_release:
  - "21.3"
  - "22.0"

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test --cover
  - mix docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: doc
  on:
    branch: master
    elixir: "1.9"
    otp_release: "22.0"
